# 编译
FROM golang:{{.goVersion}}-alpine as build

WORKDIR /build

COPY .  .

RUN CGO_ENABLED=0 GOOS=linux go build {{.modVendor}} -a -installsuffix cgo -o main -ldflags "-s -w -extldflags -static" .

# 运行
FROM scratch AS prod

WORKDIR /root/

COPY --from=build /build/main .
COPY --from=build /build/config/config.yaml ./config/config.yaml

CMD ["./main", "base"]