VERSION=0.0
GO_FLAGS= -ldflags "-w -s -X 'main.Version=$(VERSION)' -X 'main.BuildTime=`date "+%Y-%m-%d %H:%M:%S"`' -X 'main.GoVersion=`go version`' -X 'main.GitRevision=no git'"

.PHONY: build check clean test run

build: test clean
	@go build $(GO_FLAGS) -o ./bin/ ./...

check:
	@go vet ./...
	@golangci-lint run

test: check
	@go test -cover ./...

run: build
	@bin/server

clean:
	@rm -rf ./bin
